# 关闭明文 AMQP 监听，只保留 TLS 连接
listeners.tcp = none
listeners.ssl.default = 5671 # 需与 RabbitMq 默认使用的5672端口区分开

# SSL 证书配置（和容器内挂载路径对应）
ssl_options.cacertfile = /etc/rabbitmq/ssl/ca_certificate.pem
ssl_options.certfile = /etc/rabbitmq/ssl/server_certificate.pem
ssl_options.keyfile = /etc/rabbitmq/ssl/server_key.pem

# 客户端证书验证策略
ssl_options.verify = verify_peer  # 验证客户端证书
ssl_options.fail_if_no_peer_cert = true  # 要求客户端必须提供证书

# 管理界面 SSL 配置（开启 HTTPS 访问）
management.ssl.port = 15671
management.ssl.cacertfile = /etc/rabbitmq/ssl/ca_certificate.pem
management.ssl.certfile = /etc/rabbitmq/ssl/server_certificate.pem
management.ssl.keyfile = /etc/rabbitmq/ssl/server_key.pem